### PR TITLE
Create chromatermrc.alt

### PR DESCRIPTION
**Pull request by Houseman303**
My very first time submitting anything so apologies if I'm not doing it right. This is a modified config from the original ct I thought you may like. Hope it helps.

### CODE REVIEW

**Comment by hSaria** [comment]
Thank you for taking the effort to create the pull request :) 
I’ll put the majority of those highlight rules into the default CT config file. Some of the rules can be triggered with very short text (e.g. R1). Those are context-sensitive, so I’ll leave those up to the user to add.

Again, I greatly appreciate the contribution; thank you.

P.S. on one rule, there’s a line that reads GLDP. Is that right or should it be GLBP?

**Comment by hSaria** [comment]
I'll merge the config and put that into the next version of CT.

**Comment by Houseman303** [comment]
Glad to help! I think you may be right on GLBP. I can't take full credit
for the list, I adapted one I came across from the old chromaterm (or
someone on a message board or reddit thread) to the format yours uses. I
still think there may be room for improvement and will play with it when I
get a chance. One thing I noticed is on ios it highlights the interface but
it doesn't on nxos (ie Gi1/1 highlights but Eth1/1 doesn't). Thanks for
picking up where the old version left off, I use this daily. I hope to
contribute more in the future too!

**Comment by hSaria** [comment]
Thanks for the feedback. I’ll put Eth into the config file. In the meantime, you can modify the existing rule; look for the highlight rule for Cisco interfaces and you’ll find something that says `Se(rial)?|` then replace it with `Eth|Se(rial)?|`
This is assuming of course you’re using my version of the rules. If not, you can still modify or add another rule to do Eth.
If you still need help, let me know.

Thanks again for submitting this pull request.

**Pull request merged**
